name: WineCo
favicon: null
layout_spectrum: 0.35269074607640505
typography_spectrum: 0.931323494296521
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8000509720295668
  lightness: 0.136587142245844
  saturation: 0.7831384574528784
  rhythmicContrast: 0.8143410263583064
purpose: []
